### ISSUE TITLE
Installation problem - process aborted

### ISSUE THREAD

**Issue by ClaudiusBZ** [eonu/sequentia#102]
Hey guys,

unfortunately I experienced an error during installation process with `pip:`

`ERROR: Command errored out with exit status 1:
     command: 'C:\Users\...\AppData\Local\Continuum\anaconda3\envs\venv-traffic\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0]
= '"'"'C:\\Users\\...\\AppData\\Local\\Temp\\1\\pip-install-pofuzuva\\sequentia\\setup.py'"'"'; __file__='"'"'C:\\Users\\...\\AppData\\Local\\Temp\\1\\pip-install-pofuzuva\\sequentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\...\AppData\Local\Temp\1\pip-pip-egg-info-isq580ww'
         cwd: C:\Users\...\AppData\Local\Temp\1\pip-install-pofuzuva\sequentia\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\1\pip-install-pofuzuva\sequentia\setup.py", line 9, in <module>
        long_description = fh.read()
      File "C:\Users\...\AppData\Local\Continuum\anaconda3\envs\venv-traffic\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4517: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I already tried the following steps:

1. Install in another virtual environmet (clean one)
2. Install from git

Maybe you have an advice to solve the problem?

Regards
Claudius

**Comment by eonu** [comment]
Hey Claudius!

I'm not completely sure what could be causing the problem, but it seems like it could possibly be Windows related.

I've only really developed the library to run on macOS/Linux sadly, as I haven't had access to a Windows machine to test it on.

The only thing I can suggest is to try running it on a different operating system if possible, which is probably not what you wanted to hear 😢.

**Comment by ClaudiusBZ** [comment]
Hey, thank you for the fast response! Yes, a different answer would have been easier. ;)
Then I'll try another operating system.
