### ISSUE TITLE
Allow passing of extra arguments to hmmlearn and dtaidistance functions

### ISSUE THREAD

**Issue by eonu** [eonu/sequentia#122]
Currently, the package makes some assumptions when it comes to initializing the [`hmmlearn.hmm.GMMHMM`](https://hmmlearn.readthedocs.io/en/latest/api.html#gmmhmm) object (for the `GMMHMM` class), and calling the [`dtaidistance.dtw.distance`](https://dtaidistance.readthedocs.io/en/latest/modules/dtw.html#dtaidistance.dtw.distance) function (for the `KNNClassifier`). It would be useful if key-word arguments could be accepted in the `GMMHMM` and `KNNClassifier` constructors, and passed to the corresponding class/function above.

Though this may require a lot of work, and changing the overall architecture of the classes.

**Comment by jonnor** [comment]
A pragmatic approach to passing keyword arguments along to a specific subcomponent, is to have an argument like gmmhmm_kwargs={}, then expand that dictionary into keyword arguments when doing the underlying call. This is how it works in seaborn for example.

**Comment by eonu** [comment]
Eventually got to implementing it this way!

Thanks for the suggestion @jonnor 😁
