### ISSUE TITLE
Consider adding dimensionality reduction methods to preprocessing module

### ISSUE THREAD

**Issue by eonu** [eonu/sequentia#140]
Both DTW k-NN and HMM classifiers can suffer when the dimensionality of the observation sequences is too large.

It might be worth considering some dimensionality reduction methods that can be applied to time series, to the `sequentia.preprocessing` module, as a `Transform`. One possible candidate could be PCA, but I'm not sure how applicable/appropriate this is for time series.

**Comment by Prhmma** [comment]
Hi,
Do we need stand-alone dimensionality reduction in the codebase?
Because there are lots of popular libs like Sikitlearn that have these algorithms and one can use them based on their need.

**Comment by eonu** [comment]
> Hi,
> Do we need stand-alone dimensionality reduction in the codebase?
> Because there are lots of popular libs like Sikitlearn that have these algorithms and one can use them based on their need.

Hey! 

This is a fair point, we should probably keep the library as simple as possible. I honestly wouldn't know which dimensionality apply to sequential data, so it's probably best to leave it out for now. Thanks for the contributions!
