### ISSUE TITLE
DeepGRU for multivariate time series input

### ISSUE THREAD

**Issue by Vaibhav-2022** [eonu/sequentia#185]
Hello,
Thank you for sharing your work. Can you please tell me how I can use DeepGRU on a custom multivariate time series dataset? Do I need to write a custom Dataloader for it?.

**Comment by Vaibhav-2022** [comment]
@eonu Thank you for your detailed explanation. I wrote the `torch.utils.data.Dataset` in a similar way as you have written [here](https://github.com/eonu/torch-fsdd/blob/b6ec74b46e2035e449492b97430467ea9ffc1317/lib/torchfsdd/dataset.py#L154) and then used `Dataloader` to pass the data as input to the DeepGRU for training but I got a `ValueError: too many values to unpack (expected 3)`. Maybe I am missing something let me reiterate my code and get back to you.
 _Question: Do I need to create a class[ like this](https://github.com/eonu/torch-fsdd/blob/b6ec74b46e2035e449492b97430467ea9ffc1317/lib/torchfsdd/dataset.py#:~:text=class%20TorchFSDDGenerator%3A) ?._

Details of my data: I have multiple CSV files in each CSV file there are 4 columns (1 for each feature) that are timestamp synced. My idea is to combine these CSV files _(I have written code for it_)  and then pass them to the DeepGRU network for training with a label. I am not sure will the DeepGRU network accept such input (Since each column in the CSV file represents single time series and I have 4 columns in total so it forms multivariate time series ). Let me know if you need more explanation and feel free to correct if I am going wrong here.

**Comment by eonu** [comment]
So if I understand correctly:

- each CSV file represents a single time series
- the features of the time series represented by each CSV file are the 4 columns in the file

So the 4 columns in each file all have equal length, but the number of rows in each CSV file can differ, right?

Also no, you don't need to implement the generator that I created in that file, you only really need the `Dataset`, and some way of specifying which files belong to that dataset. You can see in the [`train_test_split`](https://github.com/eonu/torch-fsdd/blob/b6ec74b46e2035e449492b97430467ea9ffc1317/lib/torchfsdd/dataset.py#L77) function of the generator class, I am specifying which files belong to the training and test data, then creating the `Dataset` objects for those.

What is the piece of code you are running which causes that `ValueError`?

Your code should look something like this:

```python
# Specify files to be used to create the dataset
train_files = ['1.csv', '2.csv', '3.csv']
train_set = MyDataset(train_files)

# Create a DataLoader from the dataset
train_gen = torch.utils.data.DataLoader(train_set, collate_fn=collate_fn, batch_size=64, shuffle=True, num_workers=0)

# Initialize the model
model = DeepGRU(n_features, n_classes)

# Toggle training mode
model.train()
    
# Training loop
for batch, lengths, labels in train_gen:
    # Use batches
```

You should make sure that your `__getitem__` function in the dataset class returns a tuple of:

- a single torch tensor (with shape `n_features x n_time_steps`)
- a label for the time series

**Comment by eonu** [comment]
Closing as `classifiers.rnn` module was removed in #215.
