### ISSUE TITLE
Ideas how to interpret classifications?

### ISSUE THREAD

**Issue by franz101** [eonu/sequentia#212]
Is there a best practise for understanding which sub-sequences belong to which classes?
Or what factors the model made decide?

**Comment by eonu** [comment]
It's fairly difficult to interpret the effect of sub-sequences on classification for both the `KNNClassifier` and `DeepGRU`.

However with the `HMMClassifier`, you can inspect the state emission distributions and transition matrices for the HMMs belonging to each class. This will give you some idea about how each HMM is learning to model the sequences.

Note that `HMMClassifier` on v0.12.1/master is based on a version of `hmmlearn` that had major bugs in it. I suggest installing from the `dev` branch (which has been updated) until I make the next release.
