### ISSUE TITLE
Import error on instantiating DTWKNN

### ISSUE THREAD

**Issue by AniketVashishtha** [eonu/sequentia#95]
I am trying to use DTWKNN classifier for a classification problem of time-series data. 
I had run `pip install sequentia` successfully before executing my code. I am getting the following error from the import statement:

```Traceback (most recent call last):

  File "<ipython-input-34-abea5e5c3d19>", line 1, in <module>
    from sequentia.classifiers import DTWKNN

ImportError: cannot import name 'DTWKNN' from 'sequentia.classifiers' (/opt/anaconda3/lib/python3.7/site-packages/sequentia/classifiers/__init__.py)

**Comment by eonu** [comment]
Hey Aniket!

About two weeks ago, version 0.7.0 was released. One of the changes was the renaming of `DTWKNN` to `KNNClassifier`. The functionality still remains the same (and there is now support for distance-weighted classification too!)

I suggest you use the latest version, 0.7.1, and read the changes for 0.7.0 and 0.7.1 [here](https://github.com/eonu/sequentia/releases), and on the official documentation.

Let me know if changing to `KNNClassifier` works!
